import type { FlowProject } from "./schema";
import { validateProject } from "./validation";

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export function compileStandaloneHtml(project: FlowProject): string {
  if (validateProject(project).some((item) => item.level === "error"))
    throw new Error("Fix Flow validation errors before standalone export.");
  const serialized = JSON.stringify(project).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(project.name)} - NoaCG Flow Player</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#080c18;color:#eef4ff;font-family:Arial,sans-serif}.player{width:min(94vw,960px);padding:22px;border:1px solid #344b79;border-radius:18px;background:linear-gradient(145deg,#152443,#0e1527)}.stage{aspect-ratio:16/9;position:relative;overflow:hidden;margin:14px 0;border:1px solid #345080;border-radius:10px;background:radial-gradient(circle at 55% 45%,#243d78,#090d20 65%)}.off{position:absolute;inset:0;display:grid;place-content:center;text-align:center;letter-spacing:3px}.quiz{padding:5%;height:100%}.question{margin:5% 5% 4%;padding:3%;text-align:center;border:1px solid #78a0ff;border-radius:5px 22px;background:#24266e;font-size:clamp(12px,2.1vw,23px)}.answers{display:grid;grid-template-columns:1fr 1fr;gap:8px}.answer{display:flex;align-items:center;min-height:40px;padding:0 12px;border:1px solid #647bb6;background:#121e49}.answer b{margin-right:10px}.answer.selected{background:#79541d}.answer.correct{background:#177256}.answer.wrong{background:#7c293b}.lower{position:absolute;left:7%;bottom:12%;min-width:62%;padding:22px;border-left:5px solid #67d8c0;background:#16316d}.lower strong{display:block;font-size:clamp(22px,4vw,42px)}.data{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px;margin:12px 0}.data label{display:grid;gap:5px;font-size:11px}.data input,.data select{padding:9px;background:#0a1121;color:white;border:1px solid #405b90;border-radius:7px}.actions{display:flex;gap:8px;flex-wrap:wrap}button{padding:11px 15px;background:#1d3260;color:white;border:1px solid #5578bd;border-radius:8px;font-weight:700}</style></head>
<body><main class="player"><small>NOACG FLOW STANDALONE PLAYER</small><h1>${escapeHtml(project.name)}</h1><div id="stage" class="stage" data-renderer="${escapeHtml(project.metadata?.renderer ?? "generic")}"></div><div id="data" class="data"></div><div id="actions" class="actions"></div><p id="notice"></p></main>
<script>const project=${serialized};let runtime={stateId:project.initialStateId,variables:Object.fromEntries(project.variables.map(v=>[v.id,v.defaultValue]))};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(r,e)=>r&&typeof r==='object'?('variable'in r?runtime.variables[r.variable]:e.data?.[r.eventField]??null):r??null;
const pred=(p,e)=>{const l=val(p.left,e),r=val(p.right,e);if(p.operator==='is-set')return l!==null&&l!=='';if(p.operator==='is-not-set')return l===null||l==='';if(p.operator==='equals')return l===r;if(p.operator==='not-equals')return l!==r;if(typeof l!=='number'||typeof r!=='number')return false;if(p.operator==='greater-than')return l>r;if(p.operator==='greater-than-or-equal')return l>=r;if(p.operator==='less-than')return l<r;return l<=r};
const passes=(c,e)=>!c||(c.mode==='all'?c.predicates.every(p=>pred(p,e)):c.predicates.some(p=>pred(p,e)));
const available=()=>project.events.filter(e=>(e.source??'operator')==='operator'&&project.transitions.some(t=>(t.from===runtime.stateId||t.from==='*')&&passes(t.condition,{id:t.event,data:{}})));
const renderers={quiz:()=>{if(runtime.stateId==='off')return '<div class="off">OFF AIR</div>';const s=runtime.variables.selectedAnswer,c=runtime.variables.correctAnswer,r=runtime.stateId==='result',a=[['A','The telegraph'],['B','The phonograph'],['C','Communication satellites'],['D','The printing press']];return '<div class="quiz"><div class="question">Which invention made it possible to broadcast live pictures across the world?</div><div class="answers">'+a.map(x=>'<div class="answer '+(r?(x[0]===c?'correct':x[0]===s?'wrong':''):x[0]===s?'selected':'')+'"><b>'+x[0]+'</b>'+x[1]+'</div>').join('')+'</div></div>'},'lower-third':()=>runtime.stateId==='off'?'<div class="off">OFF AIR</div>':'<div class="lower"><strong>'+esc(runtime.variables.name)+'</strong><span>'+esc(runtime.variables.role)+'</span></div>',generic:()=>{if(runtime.stateId===project.initialStateId)return '<div class="off">OFF AIR</div>';const headline=project.variables[0];return '<div class="off"><small>'+esc(project.states.find(s=>s.id===runtime.stateId)?.label||runtime.stateId)+'</small><strong>'+esc(headline?runtime.variables[headline.id]:'')+'</strong></div>'}};
function fire(event,depth=0){if(depth>=32){notice.textContent='Emitted event safety limit reached.';return}const t=project.transitions.filter(x=>x.event===event.id&&(x.from===runtime.stateId||x.from==='*')).sort((a,b)=>a.priority-b.priority).find(x=>passes(x.condition,event));if(!t)return;t.actions.forEach(a=>{if(a.type==='set-variable')runtime.variables[a.variable]=val(a.value,event)});runtime.stateId=t.to;t.actions.filter(a=>a.type==='emit').forEach(a=>fire({id:a.event,data:Object.fromEntries(Object.entries(a.data??{}).map(([k,v])=>[k,val(v,event)]))},depth+1));notice.textContent='Ran '+(t.label||t.event)+'.';render()}
function render(){stage.innerHTML=(renderers[project.metadata?.renderer]||renderers.generic)();const editable=runtime.stateId===project.initialStateId?project.variables.filter(v=>v.operatorEditable):[];data.innerHTML=editable.map(v=>'<label>'+esc(v.label)+(v.options?'<select data-var="'+esc(v.id)+'">'+v.options.map(o=>'<option '+(o===runtime.variables[v.id]?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>':'<input data-var="'+esc(v.id)+'" value="'+esc(runtime.variables[v.id])+'">')+'</label>').join('');document.querySelectorAll('[data-var]').forEach(el=>el.onchange=()=>{runtime.variables[el.dataset.var]=el.value;render()});actions.innerHTML='';available().forEach(e=>{if(e.payload?.length===1&&e.payload[0].options){e.payload[0].options.forEach(o=>{const b=document.createElement('button');b.textContent=e.label+' '+o;b.onclick=()=>fire({id:e.id,data:{[e.payload[0].id]:o}});actions.append(b)})}else{const b=document.createElement('button');b.textContent=e.label;b.onclick=()=>fire({id:e.id,data:{}});actions.append(b)}})}render();</script></body></html>`;
}
