import type { FlowProject } from "./schema";

export function compileStandaloneHtml(project: FlowProject): string {
  const serialized = JSON.stringify(project).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${project.name} - NoaCG Flow Player</title>
<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#080c18;color:#eef4ff;font-family:Arial,sans-serif}.player{width:min(92vw,900px);padding:28px;border:1px solid #344b79;border-radius:18px;background:linear-gradient(145deg,#152443,#0e1527);box-shadow:0 24px 70px #0008}.eyebrow{color:#91b3ff;font-size:11px;font-weight:bold;letter-spacing:1.4px}.state{margin:14px 0;font-size:34px;font-weight:800}.vars{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}.var{padding:8px 10px;border-radius:8px;background:#0a1121;color:#b8c9eb;font-family:monospace}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:22px}button{border:1px solid #5578bd;border-radius:8px;padding:11px 15px;background:#1d3260;color:white;font-weight:700;cursor:pointer}button:hover{background:#294887}#notice{margin-top:16px;color:#94d9c8;font-size:13px}</style></head>
<body><main class="player"><div class="eyebrow">NOACG FLOW STANDALONE PLAYER</div><h1>${project.name}</h1><div id="state" class="state"></div><div id="vars" class="vars"></div><div id="actions" class="actions"></div><div id="notice"></div></main>
<script>const project=${serialized};let runtime={stateId:project.initialStateId,variables:Object.fromEntries(project.variables.map(v=>[v.id,v.defaultValue]))};
const value=(ref,event)=>ref&&typeof ref==='object'?('variable'in ref?runtime.variables[ref.variable]:event.value??null):ref??null;
const passes=(c,event)=>{if(!c)return true;const left=runtime.variables[c.left.variable];if(c.operator==='is-set')return left!==null&&left!=='';if(c.operator==='is-not-set')return left===null||left==='';const right=value(c.right,event);return c.operator==='equals'?left===right:left!==right};
const allowed=()=>[...new Set(project.transitions.filter(t=>(t.from===runtime.stateId||t.from==='*')&&!(t.from==='*'&&t.to===runtime.stateId)&&passes(t,{id:t.event})).map(t=>t.event))];
function render(){document.querySelector('#state').textContent=(project.states.find(s=>s.id===runtime.stateId)?.label||runtime.stateId).toUpperCase();document.querySelector('#vars').innerHTML=Object.entries(runtime.variables).map(([k,v])=>'<span class="var">'+k+': '+(v??'—')+'</span>').join('');document.querySelector('#actions').innerHTML='';allowed().forEach(id=>{const b=document.createElement('button');b.textContent=project.events.find(e=>e.id===id)?.label||id;b.onclick=()=>fire(id);document.querySelector('#actions').append(b)})}
function fire(id,valueInput){const event={id,value:valueInput};const t=project.transitions.find(x=>x.event===id&&(x.from===runtime.stateId||x.from==='*')&&passes(x,event));if(!t){document.querySelector('#notice').textContent='That action is not legal right now.';return}t.actions.forEach(a=>{if(a.type==='set-variable')runtime.variables[a.variable]=value(a.value,event)});runtime.stateId=t.to;document.querySelector('#notice').textContent='Ran '+(t.label||t.event)+'.';render()}render();</script></body></html>`;
}
