import type { FlowProject } from "./schema";

function escapeHtml(value: string) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

export function compileStandaloneHtml(project: FlowProject): string {
  const serialized = JSON.stringify(project).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(project.name)} - NoaCG Flow Player</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#080c18;color:#eef4ff;font-family:Arial,sans-serif}.player{width:min(94vw,960px);padding:22px;border:1px solid #344b79;border-radius:18px;background:linear-gradient(145deg,#152443,#0e1527);box-shadow:0 24px 70px #0008}.eyebrow{color:#91b3ff;font-size:11px;font-weight:bold;letter-spacing:1.4px}.stage{aspect-ratio:16/9;position:relative;overflow:hidden;margin:14px 0;border:1px solid #345080;border-radius:10px;background:radial-gradient(circle at 55% 45%,#243d78,#090d20 65%)}.off{position:absolute;inset:0;display:grid;place-content:center;text-align:center;color:#91a3c8;font-weight:800;letter-spacing:3px}.quiz{padding:5%;height:100%}.question{margin:5% 5% 4%;padding:3%;text-align:center;border:1px solid #78a0ff;border-radius:5px 22px;background:#24266e;font-size:clamp(12px,2.1vw,23px)}.answers{display:grid;grid-template-columns:1fr 1fr;gap:8px}.answer{display:flex;align-items:center;min-height:40px;padding:0 12px;border:1px solid #647bb6;background:#121e49}.answer b{margin-right:10px;color:#a9c2ff}.answer.selected{background:#79541d;border-color:#ffd374}.answer.correct{background:#177256;border-color:#7af0c4}.answer.wrong{background:#7c293b;border-color:#ff98a2}.lower{position:absolute;left:7%;bottom:12%;min-width:62%;padding:22px;border-left:5px solid #67d8c0;background:linear-gradient(100deg,#16316d,#19244f)}.lower strong{display:block;font-size:clamp(22px,4vw,42px)}.lower span{color:#b6c9f0}.data{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px;margin:12px 0}.data label{display:grid;gap:5px;color:#9cafcf;font-size:11px}.data input,.data select{width:100%;padding:9px;border:1px solid #405b90;border-radius:7px;background:#0a1121;color:white}.actions{display:flex;gap:8px;flex-wrap:wrap}button{border:1px solid #5578bd;border-radius:8px;padding:11px 15px;background:#1d3260;color:white;font-weight:700;cursor:pointer}button:hover{background:#294887}#notice{min-height:18px;margin-top:12px;color:#94d9c8;font-size:13px}</style></head>
<body><main class="player"><div class="eyebrow">NOACG FLOW STANDALONE PLAYER</div><h1>${escapeHtml(project.name)}</h1><div id="stage" class="stage" data-renderer="${escapeHtml(project.metadata?.renderer ?? "generic")}"></div><div id="data" class="data"></div><div id="actions" class="actions"></div><div id="notice"></div></main>
<script>const project=${serialized};let runtime={stateId:project.initialStateId,variables:Object.fromEntries(project.variables.map(v=>[v.id,v.defaultValue]))};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const value=(ref,event)=>ref&&typeof ref==='object'?('variable'in ref?runtime.variables[ref.variable]:event.value??null):ref??null;
const passes=(c,event)=>{if(!c)return true;const left=runtime.variables[c.left.variable];if(c.operator==='is-set')return left!==null&&left!=='';if(c.operator==='is-not-set')return left===null||left==='';const right=value(c.right,event);return c.operator==='equals'?left===right:left!==right};
const allowed=()=>[...new Set(project.transitions.filter(t=>(t.from===runtime.stateId||t.from==='*')&&!(t.from==='*'&&t.to===runtime.stateId)&&passes(t,{id:t.event})).map(t=>t.event))];
const renderers={quiz:()=>{if(runtime.stateId==='off')return '<div class="off">OFF AIR</div>';const selected=runtime.variables.selectedAnswer,correct=runtime.variables.correctAnswer,result=runtime.stateId==='result';const answers=[['A','The telegraph'],['B','The phonograph'],['C','Communication satellites'],['D','The printing press']];return '<div class="quiz"><div class="question">Which invention made it possible to broadcast live pictures across the world?</div><div class="answers">'+answers.map(a=>'<div class="answer '+(result?(a[0]===correct?'correct':a[0]===selected?'wrong':''):a[0]===selected?'selected':'')+'"><b>'+a[0]+'</b>'+a[1]+'</div>').join('')+'</div></div>'},'lower-third':()=>runtime.stateId==='off'?'<div class="off">OFF AIR</div>':'<div class="lower"><strong>'+esc(runtime.variables.name)+'</strong><span>'+esc(runtime.variables.role)+'</span></div>',generic:()=>'<div class="off">'+esc(project.states.find(s=>s.id===runtime.stateId)?.label||runtime.stateId)+'</div>'};
function render(){document.querySelector('#stage').innerHTML=(renderers[project.metadata?.renderer]||renderers.generic)();const editable=runtime.stateId===project.initialStateId?project.variables.filter(v=>v.operatorEditable):[];document.querySelector('#data').innerHTML=editable.map(v=>'<label>'+esc(v.label)+(v.options?'<select data-variable="'+esc(v.id)+'">'+v.options.map(o=>'<option '+(o===runtime.variables[v.id]?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>':'<input data-variable="'+esc(v.id)+'" type="'+(v.type==='number'?'number':'text')+'" value="'+esc(runtime.variables[v.id])+'">')+'</label>').join('');document.querySelectorAll('[data-variable]').forEach(el=>el.onchange=()=>{const v=project.variables.find(x=>x.id===el.dataset.variable);runtime.variables[v.id]=v.type==='number'?Number(el.value):v.type==='boolean'?el.value==='true':el.value;render()});document.querySelector('#actions').innerHTML='';allowed().forEach(id=>{const b=document.createElement('button');b.textContent=project.events.find(e=>e.id===id)?.label||id;b.onclick=()=>fire(id);document.querySelector('#actions').append(b)})}
function fire(id,eventValue){const event={id,value:eventValue};const t=project.transitions.find(x=>x.event===id&&(x.from===runtime.stateId||x.from==='*')&&passes(x,event));if(!t)return;t.actions.forEach(a=>{if(a.type==='set-variable')runtime.variables[a.variable]=value(a.value,event)});runtime.stateId=t.to;document.querySelector('#notice').textContent='Ran '+(t.label||t.event)+'.';render()}render();</script></body></html>`;
}
