"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ReactFlow, Background, Controls, Handle, MarkerType, MiniMap, Position, type Connection, type Edge, type Node, type NodeProps, type OnNodesChange } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { AlertCircle, Check, CircleDot, Download, FileUp, Link2, Plus, RotateCcw, Sparkles } from "lucide-react";
import { quizProject } from "@/flow/quiz-project";
import { availableEvents, createRuntime, dispatchEvent, type RuntimeState } from "@/flow/runtime";
import type { FlowCondition, FlowProject, FlowTransition, FlowValue } from "@/flow/schema";
import { validateProject } from "@/flow/validation";

type Selection = { kind: "state" | "transition"; id: string } | null;
type Tab = "preview" | "flow" | "controls" | "inspect";
type StateData = { label: string; active: boolean; selected: boolean; description?: string };
function StateNode({ data }: NodeProps<Node<StateData>>) { return <div className={`state-node ${data.active ? "active" : ""} ${data.selected ? "selected" : ""}`}><Handle type="target" position={Position.Left} /><i /><strong>{data.label}</strong><span>{data.active ? "LIVE STATE" : data.description || "Flow state"}</span><Handle type="source" position={Position.Right} /></div>; }
const nodeTypes = { state: StateNode };
const names: Record<string, string> = { TAKE: "Take", LOCK: "Lock", REVEAL: "Reveal", TAKE_OUT: "Take out", RESET: "Reset" };
const textCondition = (condition?: FlowCondition) => !condition ? "Always available" : condition.operator === "is-set" ? `${condition.left.variable} has a value` : condition.operator === "is-not-set" ? `${condition.left.variable} has no value` : `${condition.left.variable} ${condition.operator === "equals" ? "equals" : "does not equal"} ${condition.right && typeof condition.right === "object" && "variable" in condition.right ? condition.right.variable : JSON.stringify(condition.right)}`;
const textAction = (action: FlowTransition["actions"][number]) => action.type === "play-animation" ? `Play “${action.animation}”` : action.type === "set-variable" ? `Set ${action.variable}` : `Emit ${action.event}`;
function saveFile(name: string, content: string) { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); a.download = name; a.click(); URL.revokeObjectURL(a.href); }
function loadStoredProject(): FlowProject { if (typeof window === "undefined") return quizProject; try { const raw = localStorage.getItem("noacg-flow-lab-project"); return raw ? JSON.parse(raw) as FlowProject : quizProject; } catch { return quizProject; } }

export default function FlowLab() {
  const [project, setProject] = useState<FlowProject>(loadStoredProject);
  const [runtime, setRuntime] = useState<RuntimeState>(() => createRuntime(loadStoredProject()));
  const [selection, setSelection] = useState<Selection>({ kind: "state", id: "off" });
  const [tab, setTab] = useState<Tab>("preview");
  const [notice, setNotice] = useState("Ready for air.");
  const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { localStorage.setItem("noacg-flow-lab-project", JSON.stringify(project)); }, [project]);
  const dispatch = useCallback((id: string, value?: FlowValue) => { const result = dispatchEvent(project, runtime, { id, value }); setRuntime(result.runtime); if (result.ok) { setSelection({ kind: "transition", id: result.transitionId }); setNotice(`Ran ${result.transitionId.replaceAll("-", " ")}.`); } else setNotice(result.reason); }, [project, runtime]);
  const allowed = useMemo(() => availableEvents(project, runtime), [project, runtime]);
  const diagnostics = useMemo(() => validateProject(project), [project]);
  const state = selection?.kind === "state" ? project.states.find((item) => item.id === selection.id) : undefined;
  const transition = selection?.kind === "transition" ? project.transitions.find((item) => item.id === selection.id) : undefined;
  const nodes = useMemo<Node<StateData>[]>(() => project.states.map((item) => ({ id: item.id, type: "state", position: item.position, width: 147, height: 76, sourcePosition: Position.Right, targetPosition: Position.Left, data: { label: item.label, description: item.description, active: runtime.stateId === item.id, selected: selection?.kind === "state" && selection.id === item.id } })), [project.states, runtime.stateId, selection]);
  const edges = useMemo<Edge[]>(() => project.transitions.filter((item) => item.from !== "*").map((item) => ({ id: item.id, source: item.from, target: item.to, label: item.label ?? item.event, animated: runtime.lastTransitionId === item.id, markerEnd: { type: MarkerType.ArrowClosed }, className: `${selection?.kind === "transition" && selection.id === item.id ? "flow-edge-selected" : ""} ${runtime.lastTransitionId === item.id ? "flow-edge-fired" : ""}`, labelStyle: { fill: "#c3d1ff", fontSize: 11, fontWeight: 700 }, labelBgStyle: { fill: "#10172b", fillOpacity: 0.94 } })), [project.transitions, runtime.lastTransitionId, selection]);
  const onNodesChange: OnNodesChange = useCallback((changes) => setProject((current) => ({ ...current, states: current.states.map((item) => { const change = changes.find((entry) => entry.type === "position" && entry.id === item.id && entry.position); return change?.type === "position" && change.position ? { ...item, position: change.position } : item; }) })), []);
  const onConnect = useCallback((connection: Connection) => { if (!connection.source || !connection.target) return; const event = prompt("Trigger name, e.g. CONTINUE"); if (!event) return; setProject((current) => ({ ...current, events: current.events.some((item) => item.id === event) ? current.events : [...current.events, { id: event, label: event }], transitions: [...current.transitions, { id: `transition-${crypto.randomUUID()}`, from: connection.source!, to: connection.target!, event, label: event, actions: [{ type: "play-animation", animation: "transition" }] }] })); }, []);
  const addState = () => { const label = prompt("State name", "NEW STATE"); if (!label?.trim()) return; const id = label.toLowerCase().replace(/[^a-z0-9]+/g, "-") || `state-${Date.now()}`; setProject((current) => ({ ...current, states: [...current.states, { id, label: label.toUpperCase(), description: "A new stable graphic state.", position: { x: 340, y: 430 } }] })); setSelection({ kind: "state", id }); };
  const addVariable = () => { const label = prompt("Variable name", "newValue"); if (!label?.trim()) return; const id = label.replace(/\W/g, "") || `value${Date.now()}`; setProject((current) => ({ ...current, variables: [...current.variables, { id, label, type: "string", defaultValue: "" }] })); };
  const loadFile = (file: File) => { const r = new FileReader(); r.onload = () => { try { const next = JSON.parse(String(r.result)) as FlowProject; if (!next.states || !next.transitions || !next.variables) throw new Error(); setProject(next); setRuntime(createRuntime(next)); setNotice("Flow project imported."); } catch { setNotice("That file is not a valid Flow project."); } }; r.readAsText(file); };
  const stateName = project.states.find((item) => item.id === runtime.stateId)?.label || runtime.stateId;
  return <main className="lab-shell"><header className="topbar"><div className="brand"><b><CircleDot size={20} /></b><div><strong>NoaCG <i>Flow Lab</i></strong><small>Visual behavior for live HTML graphics</small></div></div><div className="topbar-actions"><span><Check size={14} /> Saved locally</span><button onClick={() => saveFile("noacg-flow-project.json", JSON.stringify(project, null, 2))} title="Export Flow JSON"><Download size={16} /></button><button onClick={() => importRef.current?.click()} title="Import Flow JSON"><FileUp size={16} /></button><input ref={importRef} hidden type="file" accept="application/json" onChange={(event) => event.target.files?.[0] && loadFile(event.target.files[0])} /></div></header>
    <nav className="mobile-tabs"><button className={tab === "preview" ? "active" : ""} onClick={() => setTab("preview")}>Preview</button><button className={tab === "flow" ? "active" : ""} onClick={() => setTab("flow")}>Flow</button><button className={tab === "controls" ? "active" : ""} onClick={() => setTab("controls")}>Controls</button><button className={tab === "inspect" ? "active" : ""} onClick={() => setTab("inspect")}>Inspect</button></nav>
    <section className={`workspace tab-${tab}`}><div className="left-column"><section className="panel preview-panel"><Title eyebrow="Live preview" title="Quiz question" right={<span className="state-pill"><i />{stateName}</span>} /><QuizPreview runtime={runtime} /><div className="preview-foot"><span><Sparkles size={14} /> {runtime.lastAnimation ? `Animation: ${runtime.lastAnimation}` : "Waiting for first transition"}</span><span>16:9 output</span></div></section><section className="panel runtime-panel"><Title eyebrow="Runtime" title="Live values" /><div className="variable-list">{project.variables.map((item) => <div key={item.id}><span>{item.label}<small>{item.id}</small></span><strong>{runtime.variables[item.id] === null ? "—" : String(runtime.variables[item.id])}</strong></div>)}</div></section></div>
      <section className="panel graph-panel"><Title eyebrow="State graph" title={project.name} right={<div className="graph-actions"><button onClick={addState}><Plus size={14} /> State</button><button onClick={() => setNotice("Drag from a state handle to another state to connect them.")}><Link2 size={14} /> Connect</button></div>} /><div className="graph-canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onConnect={onConnect} onNodeClick={(_, node) => setSelection({ kind: "state", id: node.id })} onEdgeClick={(_, edge) => setSelection({ kind: "transition", id: edge.id })} onInit={(instance) => { window.setTimeout(() => instance.fitView({ padding: 0.12 }), 0); }} fitView minZoom={0.4} maxZoom={1.5} proOptions={{ hideAttribution: true }}><Background color="#263558" gap={20} size={1} /><MiniMap nodeColor={(node) => node.id === runtime.stateId ? "#79a6ff" : "#26385d"} maskColor="rgba(8,12,25,.7)" /><Controls showInteractive={false} /></ReactFlow><div className="graph-transition-rail">{project.transitions.filter((item, index, list) => item.from !== "*" && item.from !== item.to && list.findIndex((other) => other.from === item.from && other.to === item.to && other.event === item.event) === index).map((item) => <button key={item.id} onClick={() => setSelection({ kind: "transition", id: item.id })}>{item.event}</button>)}</div></div><div className="graph-note"><span><i className="dot live" /> Active state</span><span><i className="dot fired" /> Last transition</span><span>Global: {project.transitions.filter((item) => item.from === "*").map((item) => item.label).join(" · ")}</span></div></section>
      <div className="right-column"><section className="panel controls-panel"><Title eyebrow="Operator controls" title="Only legal actions" /><p>{project.states.find((item) => item.id === runtime.stateId)?.description}</p>{allowed.includes("SELECT_ANSWER") && <div className="answer-controls">{["A", "B", "C", "D"].map((answer) => <button key={answer} className={runtime.variables.selectedAnswer === answer ? "selected" : ""} onClick={() => dispatch("SELECT_ANSWER", answer)}>{answer}</button>)}</div>}<div className="command-controls">{allowed.filter((event) => event !== "SELECT_ANSWER").map((event) => <button key={event} className={event === "TAKE" || event === "REVEAL" ? "primary" : event === "RESET" ? "quiet" : ""} onClick={() => dispatch(event)}>{names[event] || event}</button>)}</div><div className={`notice ${notice.includes("not ") ? "warning" : ""}`}>{notice.includes("not ") ? <AlertCircle size={15} /> : <Check size={15} />}{notice}</div></section>
      <section className="panel inspector-panel"><Title eyebrow="Inspector" title={transition ? "Transition" : state ? "State" : "Select a graph item"} />{state && <div className="inspector-content"><label>Name<input value={state.label} onChange={(event) => setProject((current) => ({ ...current, states: current.states.map((item) => item.id === state.id ? { ...item, label: event.target.value } : item) }))} /></label><label>Description<textarea value={state.description || ""} onChange={(event) => setProject((current) => ({ ...current, states: current.states.map((item) => item.id === state.id ? { ...item, description: event.target.value } : item) }))} /></label><p>A state is a stable on-air situation. Changing values belong in variables.</p></div>}{transition && <div className="inspector-content"><label>Trigger<select value={transition.event} onChange={(event) => setProject((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, event: event.target.value, label: event.target.value } : item) }))}>{project.events.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><Info label="From" value={transition.from === "*" ? "Any state (global)" : project.states.find((item) => item.id === transition.from)?.label || transition.from} /><Info label="To" value={project.states.find((item) => item.id === transition.to)?.label || transition.to} /><Info label="Condition" value={textCondition(transition.condition)} /><div className="action-list"><small>ACTIONS</small>{transition.actions.map((action, index) => <div key={index}><b>{index + 1}</b>{textAction(action)}</div>)}</div></div>}</section>
      <section className="panel validation-panel"><Title eyebrow="Flow health" title={diagnostics.some((item) => item.level === "error") ? "Needs attention" : "Looking good"} />{diagnostics.length ? diagnostics.map((item, i) => <div className={`diagnostic ${item.level}`} key={i}><AlertCircle size={14} />{item.message}</div>) : <div className="diagnostic okay"><Check size={14} /> No structural issues found.</div>}<button className="text-action" onClick={addVariable}><Plus size={14} /> Define variable</button><button className="text-action" onClick={() => { setProject(quizProject); setRuntime(createRuntime(quizProject)); setNotice("Reference quiz restored."); }}><RotateCcw size={14} /> Restore quiz reference</button></section></div></section></main>;
}
function Title({ eyebrow, title, right }: { eyebrow: string; title: string; right?: React.ReactNode }) { return <div className="panel-title"><div><small>{eyebrow}</small><h2>{title}</h2></div>{right}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="info-row"><small>{label}</small><span>{value}</span></div>; }
function QuizPreview({ runtime }: { runtime: RuntimeState }) { const visible = runtime.stateId !== "off"; const selected = String(runtime.variables.selectedAnswer || ""); const correct = String(runtime.variables.correctAnswer || ""); return <div className={`quiz-frame ${visible ? "on-air" : "off-air"}`}><div className="quiz-glow" />{visible ? <div className="quiz-output" key={runtime.revision}><div className="quiz-topline"><span>LIVE QUIZ</span><b>£ 64,000</b></div><div className="question-card"><small>QUESTION 07</small><h3>Which invention made it possible to broadcast live pictures across the world?</h3></div><div className="answers">{[["A", "The telegraph"], ["B", "The phonograph"], ["C", "Communication satellites"], ["D", "The printing press"]].map(([letter, copy], i) => { const picked = selected === letter; const isCorrect = correct === letter; const result = runtime.stateId === "result"; const tone = result ? isCorrect ? "correct" : picked ? "wrong" : "" : picked ? runtime.stateId === "locked" ? "locked" : "chosen" : ""; return <div className={`answer ${tone}`} style={{ animationDelay: `${.18 + i * .08}s` }} key={letter}><span>{letter}</span><p>{copy}</p>{result && isCorrect && <b>✓</b>}</div>; })}</div><div className="quiz-status">{runtime.stateId === "locked" ? "ANSWER LOCKED" : runtime.stateId === "result" ? selected === correct ? "CORRECT" : "RESULT" : ""}</div></div> : <div className="off-air-message"><span>PROGRAM</span><strong>OFF AIR</strong><small>Take to begin the question</small></div>}</div>; }
